version: '3'

services:

  postgres:
    image: postgres:15

    environment:
      POSTGRES_DB: riskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  backend:
    build: ./backend

    ports:
      - "8087:8085"

    depends_on:
      - postgres