server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/riskdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true